// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0-devel
// 	protoc        v3.11.4
// source: data.proto

package main

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ChunkMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChunkIndex uint32         `protobuf:"varint,1,opt,name=chunkIndex,proto3" json:"chunkIndex,omitempty"`
	WorldSizeX uint32         `protobuf:"varint,2,opt,name=worldSizeX,proto3" json:"worldSizeX,omitempty"`
	WorldSizeY uint32         `protobuf:"varint,3,opt,name=worldSizeY,proto3" json:"worldSizeY,omitempty"`
	Ticks      []*TickMessage `protobuf:"bytes,4,rep,name=ticks,proto3" json:"ticks,omitempty"`
}

func (x *ChunkMessage) Reset() {
	*x = ChunkMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChunkMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkMessage) ProtoMessage() {}

func (x *ChunkMessage) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkMessage.ProtoReflect.Descriptor instead.
func (*ChunkMessage) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{0}
}

func (x *ChunkMessage) GetChunkIndex() uint32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *ChunkMessage) GetWorldSizeX() uint32 {
	if x != nil {
		return x.WorldSizeX
	}
	return 0
}

func (x *ChunkMessage) GetWorldSizeY() uint32 {
	if x != nil {
		return x.WorldSizeY
	}
	return 0
}

func (x *ChunkMessage) GetTicks() []*TickMessage {
	if x != nil {
		return x.Ticks
	}
	return nil
}

type TickMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TickIndex uint64        `protobuf:"varint,1,opt,name=tickIndex,proto3" json:"tickIndex,omitempty"`
	Bots      []*BotMessage `protobuf:"bytes,2,rep,name=bots,proto3" json:"bots,omitempty"`
}

func (x *TickMessage) Reset() {
	*x = TickMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TickMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickMessage) ProtoMessage() {}

func (x *TickMessage) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickMessage.ProtoReflect.Descriptor instead.
func (*TickMessage) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{1}
}

func (x *TickMessage) GetTickIndex() uint64 {
	if x != nil {
		return x.TickIndex
	}
	return 0
}

func (x *TickMessage) GetBots() []*BotMessage {
	if x != nil {
		return x.Bots
	}
	return nil
}

type BotMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index  uint64          `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	CoordX uint32          `protobuf:"varint,2,opt,name=coordX,proto3" json:"coordX,omitempty"`
	CoordY uint32          `protobuf:"varint,3,opt,name=coordY,proto3" json:"coordY,omitempty"`
	Energy uint32          `protobuf:"varint,4,opt,name=energy,proto3" json:"energy,omitempty"`
	Genome []byte          `protobuf:"bytes,5,opt,name=genome,proto3" json:"genome,omitempty"`
	Organs []*OrganMessage `protobuf:"bytes,6,rep,name=organs,proto3" json:"organs,omitempty"`
}

func (x *BotMessage) Reset() {
	*x = BotMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotMessage) ProtoMessage() {}

func (x *BotMessage) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotMessage.ProtoReflect.Descriptor instead.
func (*BotMessage) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{2}
}

func (x *BotMessage) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BotMessage) GetCoordX() uint32 {
	if x != nil {
		return x.CoordX
	}
	return 0
}

func (x *BotMessage) GetCoordY() uint32 {
	if x != nil {
		return x.CoordY
	}
	return 0
}

func (x *BotMessage) GetEnergy() uint32 {
	if x != nil {
		return x.Energy
	}
	return 0
}

func (x *BotMessage) GetGenome() []byte {
	if x != nil {
		return x.Genome
	}
	return nil
}

func (x *BotMessage) GetOrgans() []*OrganMessage {
	if x != nil {
		return x.Organs
	}
	return nil
}

type OrganMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParentBotIndex uint64 `protobuf:"varint,1,opt,name=parentBotIndex,proto3" json:"parentBotIndex,omitempty"`
	OrganIndex     uint64 `protobuf:"varint,2,opt,name=organIndex,proto3" json:"organIndex,omitempty"`
	CoordX         uint32 `protobuf:"varint,3,opt,name=coordX,proto3" json:"coordX,omitempty"`
	CoordY         uint32 `protobuf:"varint,4,opt,name=coordY,proto3" json:"coordY,omitempty"`
	Genome         []byte `protobuf:"bytes,5,opt,name=genome,proto3" json:"genome,omitempty"`
}

func (x *OrganMessage) Reset() {
	*x = OrganMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrganMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganMessage) ProtoMessage() {}

func (x *OrganMessage) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganMessage.ProtoReflect.Descriptor instead.
func (*OrganMessage) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{3}
}

func (x *OrganMessage) GetParentBotIndex() uint64 {
	if x != nil {
		return x.ParentBotIndex
	}
	return 0
}

func (x *OrganMessage) GetOrganIndex() uint64 {
	if x != nil {
		return x.OrganIndex
	}
	return 0
}

func (x *OrganMessage) GetCoordX() uint32 {
	if x != nil {
		return x.CoordX
	}
	return 0
}

func (x *OrganMessage) GetCoordY() uint32 {
	if x != nil {
		return x.CoordY
	}
	return 0
}

func (x *OrganMessage) GetGenome() []byte {
	if x != nil {
		return x.Genome
	}
	return nil
}

var File_data_proto protoreflect.FileDescriptor

var file_data_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x92, 0x01, 0x0a,
	0x0c, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1e, 0x0a,
	0x0a, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x58, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x58, 0x12, 0x1e, 0x0a,
	0x0a, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x59, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x59, 0x12, 0x22, 0x0a,
	0x05, 0x74, 0x69, 0x63, 0x6b, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x54,
	0x69, 0x63, 0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x74, 0x69, 0x63, 0x6b,
	0x73, 0x22, 0x4c, 0x0a, 0x0b, 0x54, 0x69, 0x63, 0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x63, 0x6b, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x63, 0x6b, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1f,
	0x0a, 0x04, 0x62, 0x6f, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x42,
	0x6f, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x62, 0x6f, 0x74, 0x73, 0x22,
	0xa9, 0x01, 0x0a, 0x0a, 0x42, 0x6f, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x58, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x58, 0x12, 0x16, 0x0a, 0x06,
	0x63, 0x6f, 0x6f, 0x72, 0x64, 0x59, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x6f,
	0x6f, 0x72, 0x64, 0x59, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x67, 0x65, 0x6e, 0x6f, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x67, 0x65,
	0x6e, 0x6f, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x06, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x73, 0x22, 0x9e, 0x01, 0x0a, 0x0c,
	0x4f, 0x72, 0x67, 0x61, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x0e,
	0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x42, 0x6f, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x42, 0x6f, 0x74, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x58, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x58, 0x12, 0x16, 0x0a, 0x06,
	0x63, 0x6f, 0x6f, 0x72, 0x64, 0x59, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x6f,
	0x6f, 0x72, 0x64, 0x59, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x6f, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x6f, 0x6d, 0x65, 0x42, 0x08, 0x5a, 0x06,
	0x2e, 0x3b, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_data_proto_rawDescOnce sync.Once
	file_data_proto_rawDescData = file_data_proto_rawDesc
)

func file_data_proto_rawDescGZIP() []byte {
	file_data_proto_rawDescOnce.Do(func() {
		file_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_proto_rawDescData)
	})
	return file_data_proto_rawDescData
}

var file_data_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_data_proto_goTypes = []interface{}{
	(*ChunkMessage)(nil), // 0: ChunkMessage
	(*TickMessage)(nil),  // 1: TickMessage
	(*BotMessage)(nil),   // 2: BotMessage
	(*OrganMessage)(nil), // 3: OrganMessage
}
var file_data_proto_depIdxs = []int32{
	1, // 0: ChunkMessage.ticks:type_name -> TickMessage
	2, // 1: TickMessage.bots:type_name -> BotMessage
	3, // 2: BotMessage.organs:type_name -> OrganMessage
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_data_proto_init() }
func file_data_proto_init() {
	if File_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChunkMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TickMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrganMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_proto_goTypes,
		DependencyIndexes: file_data_proto_depIdxs,
		MessageInfos:      file_data_proto_msgTypes,
	}.Build()
	File_data_proto = out.File
	file_data_proto_rawDesc = nil
	file_data_proto_goTypes = nil
	file_data_proto_depIdxs = nil
}
